##Does the quality or target audience of a movie effect its box office returns? (Joe)

```{r, warning=FALSE, message=FALSE}
library(tidyverse)
library(ggplot2)
movies <- read_csv("movies.csv")

blockbuster <- movies %>% select('title', 'adjusted', 'audience_freshness', 'rt_freshness') %>% filter(audience_freshness > 90) %>% filter(rt_freshness < 90) %>% arrange(desc(adjusted)) %>% slice(1:5) %>% mutate(stringr::str_trunc(title, 20))
colnames(blockbuster)[5] <- "newname"
bavg <- blockbuster %>% select('adjusted') %>% map(mean)
bavg

oscarbait <- movies %>% select('title', 'adjusted', 'rt_freshness', 'audience_freshness') %>% filter(rt_freshness > 90) %>% filter(audience_freshness < 80) %>% arrange(desc(adjusted)) %>% slice(1:5) %>% mutate(stringr::str_trunc(title, 20)) 
colnames(oscarbait)[5] <- "newname"
oavg <- oscarbait %>% select('adjusted') %>% map(mean)
oavg

excellence <- movies %>% select('title', 'adjusted', 'audience_freshness', 'rt_freshness') %>% filter(audience_freshness > 90) %>% filter(rt_freshness > 90) %>% arrange(desc(adjusted)) %>% slice(1:6) %>% mutate(stringr::str_trunc(title, 20))
colnames(excellence)[5] <- "newname"
eavg <- excellence %>% select('adjusted') %>% map(mean)
eavg

trash <- movies %>% select('title', 'adjusted', 'audience_freshness', 'rt_freshness') %>% filter(audience_freshness < 50) %>% filter(rt_freshness < 50) %>% arrange(desc(adjusted)) %>% slice(1:5) %>% mutate(stringr::str_trunc(title, 20))
tavg <- trash %>% select('adjusted') %>% map(mean)
tavg

ggplot()+
  geom_col(data = blockbuster, mapping = aes(x = newname, y = adjusted))+
  labs(title = "Top 5 Grossing Crowdpleasers", x = "Movie Title", y = "Box Office Gross")+
  geom_hline(yintercept = 867308679)
ggplot()+
  geom_col(data = oscarbait, mapping = aes(x = newname, y = adjusted))+
  labs(title = "Top 5 Grossing Critic Pleasers", x = "Movie Title", y = "Box Office Gross")+
  geom_hline(yintercept = 764569664)
ggplot()+
  geom_col(data = excellence, mapping = aes(x = newname, y = adjusted))+
  labs(title = "Top 5 Grossing Movies Loved by Audience and Critics", x = "Movie Title", y = "Box Office Gross")+
  geom_hline(yintercept = 1188399713)
ggplot()+
  geom_col(data = trash, mapping = aes(x = title, y = adjusted))+
  labs(title = "Top 5 Grossing Disliked Movies", x = "Movie Title", y = "Box Office Gross")+
  geom_hline(yintercept = 622350515)
```
**My question is interesting because it shows that investing resources and passion into making a good movie usually rewards everyone at the box office. The audience is happy, the critics are happy, and the production company is hauling in the cash. Making the best movie possible maximizes social surplus.**

**I used the mapping tool from purrr to grab the average of a whole collumn of values from each tibble.**

**Movies that are well liked by audience and critics to far better than any other category of movie. Movies that only critics like seem to do the worst. This lets production companies know that it is very much so worth it to create the best movie possible. If this were obeyed by every production studio in Hollywood, more high quality movies would be made instead of movies that are attempting to grab a quick profit.**

**I believe that this shows that movie studios in Hollywood are not only unethical with their systematic destruction of established titles, but they're not even being efficient with there money making. They're just being lazy.**

**My six-month goal is the same still. I just want to study something that is interesting to me and applicable in a workspace without spending more than six years here. My five year goal has changed. I think that it would be perfectly fine for me to be working an office job, as long as the office is a supportive and comfortable place to work. I learned a lot about coding this semester and even more about working in groups. I realized how much easier work goes when a team works as one. I wish that we had started working as a team earlier on into the year. I would also tell myself to stop staying up so late and to keep asking questions when I needed help.**