---
title: "Lab 8"
author: "Spicy Bois"
date: "10/17/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
```


# Who is hiring us?
**Domain Expert**

# Overall Question (TEAM)
**Question:**
**Why is it important/interesting:**

# Description of the Dataset

# Individual Questions
## Question ()
**Why is it important/interesting:**

# Visualizations
## Challa (Joe)
```{r}

```

## Tanganyika (Trent)
```{r}

```

## Malawi (Tyler)
```{r}

```

## CRU and MAM Rainfall (Jack)
```{r}

```


## VOI Rainfall (Logan)
```{r, message=FALSE}
VOI_Rainfall <- read_excel("East Africa lake data.xlsx", sheet = "VOI rainfall station data")
VOI_Rainfall_tidy <- VOI_Rainfall %>% select(-c(`...14`, `...15`)) %>% 
  gather("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec", key = "Month", value = "Rainfall") %>%
  mutate(Month = if_else(Month == "Jan", 1, if_else(Month == "Feb", 2, if_else(Month == "Mar", 3, if_else(Month == "Apr", 4, if_else(Month == "May", 5, if_else(Month == "Jun", 6, if_else(Month == "Jul", 7, if_else(Month == "Aug", 8, if_else(Month == "Sep", 9, if_else(Month == "Oct", 10, if_else(Month == "Nov", 11, if_else(Month == "Dec", 12, 0))))))))))))) %>% 
  arrange(Year) %>%
  filter(!is.na(Rainfall))

labels <- c(Female = "Women", Male = "Men")

ggplot(VOI_Rainfall_tidy, aes(x = Year, y = Rainfall)) + 
  facet_wrap(.~Month, labeller=labeller(Month =  c(`1` = "January", `2` = "February", `3` = "March", `4` = "April", `5` = "May", `6` = "June", `7` = "July", `8` = "August", `9` = "September", `10` = "October", `11` = "November", `12` = "December"))) + 
  geom_line() + 
  labs(title = "VOI Rainfall for every month vs. year", y = "Rainfall (cm)", x = "Year")
```




