---
title: "Lab11"
author: "Spicy Bois"
date: "11/4/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(babynames)
library(stringr)
```

# Lab 11

```{r}
data <- babynames
babies2018 <- read.csv(file = "yob2018.txt", header= FALSE)
colnames(babies2018) <- c("name", "sex","n")
babies2018$year <- rep(2018,nrow(babies2018))
babies2018$prop = babies2018$n / sum(babies2018$n)
babies2018

totalbabies <- full_join(babynames, babies2018)
totalbabies
```


```{r}
library(tidyverse)
library(babynames)
library(stringr)

data <- totalbabies


findName <- data %>%
  filter(str_detect(name, "^A[r]+[iyea][ea][l]+[ea]*$") | (str_detect(name, "^R[ae][aey]?[ch]+[aey]+[l]+e*$"))) %>% 
  filter(year %in% list(1973, 1988, 1990)) %>% 
  filter(sex == 'F')

findRachel <- data %>%
  filter(str_detect(name, "^R[ae][aey]?[ch]+[aey]+[l]+e*$")) %>% 
  filter(year %in% list(1973, 1988, 1990)) %>% 
  filter(sex == 'F')

names <- findName %>% 
  group_by(year, initial = str_sub(name, 1, 1), prop) %>% 
  summarize(variants = n())

findName
names

ggplot(data = names, mapping = aes(x = initial, y = prop, fill = initial))+
  geom_col()+
  facet_wrap(~year)+
  labs(title = "Baby Names and Their Proportion of the Population By Year", x = "Names (All Versions of Ariel and Rachel)", y = "Proportion of Babies w/ that Name")+
  theme_bw()
```

**Jack Braglia's Graphs**
```{r}
library(tidyverse)
library(babynames)
library(stringr)

data <- totalbabies

findMyName <- data %>% 
  filter(str_detect(name, "^Jac")) %>% 
  filter(sex == 'M')

findJack <- data %>% 
  filter(str_detect(name, "^Jack$")) %>% 
  filter(sex == 'M')

findJackAlive <- data %>% 
  filter(str_detect(name, "^Jack$")) %>% 
  filter(sex == 'M') %>% 
  filter(year >= 1998)

mynames <- findMyName %>% 
  group_by(year, initial = str_sub(name, 1, 1), prop) %>% 
  summarize(variants = n())

myJack <- findJack %>% 
  group_by(year, initial = str_sub(name, 1, 1), prop) %>% 
  summarize(variants = n())

myJackAlive <- findJackAlive %>% 
  group_by(year, initial = str_sub(name, 1, 1), prop) %>% 
  summarize(variants = n())

ggplot(data = mynames, mapping = aes(x = year, y = prop))+
  facet_wrap(~initial)+
  geom_col()+
  labs(title = "Baby Names and Their Proportion of the Population from 1880-2018", x = "Names Starting with 'Jac'", y = "Proportion of Babies w/ that Name")+
  theme_bw()

ggplot(data = myJack, mapping = aes(x = year, y = prop))+
  facet_wrap(~initial)+
  geom_col()+
  labs(title = "Popularity of 'Jack' from 1880-2018", x = "Baby Named 'Jack'", y = "Proportion of Babies w/ Name Jack")+
  theme_bw()

ggplot(data = myJackAlive, mapping = aes(x = year, y = prop))+
  facet_wrap(~initial)+
  geom_col()+
  labs(title = "Popularity of 'Jack' from 1998-2018", x = "Baby Named 'Jack'", y = "Proportion of Babies w/ Name Jack")+
  theme_bw()

goodnames <- data %>% 
  filter(prop <= .001) %>% 
  filter(prop >= .0005) %>% 
  filter(year >= 2010) %>% 
  filter(sex == 'M')

findDelilah <- data %>% 
  filter(str_detect(name, "^Delilah$")) %>% 
  filter(year >= 2010) %>% 
  filter(sex == 'F')

findJosue <- data %>% 
  filter(str_detect(name, "^Zion$")) %>% 
  filter(year >= 2010) %>% 
  filter(sex == 'M')

findDelilah
findJosue
goodnames

  

```

How popular is your name now compared to when you were born? 

My name is slightly more popular than it was when I was born according to the proportion the name was given to the population. The pro

How popular is your name now relative to the other names that start with the same three letters?


